### ISSUE TITLE
[BUG] Pull Request 0

### ISSUE THREAD

**Issue by TheFaR8** [CCExtractor/sample-platform#119] opened 2017-12-02 15:48 UTC
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/sample-platform/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [x] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [ ] I am an active contributor to the platform.

---

![screenshot from 2017-12-02 22-31-28](https://user-images.githubusercontent.com/31211200/33517230-d637b03c-d7b2-11e7-9d38-cdb5f0943162.png)

I saw this bug when I just opened sample platform to see the progress of my current pull request

**Comment by canihavesomecoffee** [comment] 2017-12-02 15:59
@TheFaR8 That's maybe caused by you closing and re-opening the PR. If you want to try and solve it yourself, I can make a task for it.

**Comment by TheFaR8** [comment] 2017-12-02 16:28
Still got no clue though
I think that might be the problem

**Closed** 2017-12-13 19:45 UTC
