### ISSUE TITLE
Add unit/integration tests

### ISSUE THREAD

**Issue by canihavesomecoffee** [CCExtractor/sample-platform#62] opened 2017-03-12 16:01 UTC
Currently, the sample platform has no unit/integration tests. This is not ideal, so some tests should be added.

Flask provides [a way to test the application](http://flask.pocoo.org/docs/0.12/testing/), so it'd be great to make use of that and test some stuff that way.

If this is implemented, an integration with GitHub could be added to ensure that Pull Requests aren't breaking anything anymore too.

**Comment by mansimarkaur** [comment] 2017-03-14 11:54
I'd like to work on this.

**Comment by canihavesomecoffee** [comment] 2017-03-14 14:11
You can start working on it without asking for permission ;) Just open a PR when you're done

**Comment by sanchaymittal** [comment] 2018-02-17 23:14
Can I work on this issue.
If yes, please fill me with the details.

**Comment by saurabhshri** [comment] 2018-02-18 07:44
@sanchaymittal You don't need to ask, just work :) . Regarding details - do you have a specific question?

**Comment by sanchaymittal** [comment] 2018-02-18 08:02
@saurabhshri Acknowledged  :grin:
Not specific but any detail regarding the issue will be helpful.

**Comment by thealphadollar** [comment] 2019-06-17 20:46
duplicate of #284 but since unit-tests can be always improved and made better and more precise, this should stay open forever :smile:

**Closed** 2023-02-17 20:42 UTC
Labels: enhancement, help wanted, hacktoberfest-accepted
